{% set version = "1.2.1" %}
{% set build = 0 %}


{% set interface = interface or 'nogui' %}
{% set processor = processor or 'cpu' %}

{% if interface == "gui" %}
# prioritize full gui version via build number
{% set build = build + 100 %}
{% endif %}



package:
  name: "prismatic"
  version: {{ version }}

source:
  url: https://github.com/prism-em/prismatic/archive/{{ version }}.tar.gz
  sha256: 844f659575dd98999b7c4864e850a7ec735f297ab1fb6c2d2be91d7f9720fe70 

build:
  number: {{ build }}
  skip: True             # [win]
  string: "{{ interface }}_{{processor}}_h{{ PKG_HASH }}_{{ build }}"


requirements:
  build:
    - python 3.*
    - {{ compiler('c') }}                
    - {{ compiler('cxx') }}              
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - make                               # [unix]
    - cmake
    - pip                                
  host:
    - python 3.*                       
    - boost
    - hdf5
    - fftw
    - qt 5.9.*                           # [linux and interface == 'gui']
    - qt                                 # [not linux and interface == 'gui']
    - numpy
    - h5py
    - zlib
  run:
    - python 3.*  
    - numpy
    - h5py       
    - fftw
    - libcxx                             # [osx]

test:
  source_files:
    - SI100.XYZ                          
  commands:
    - command -v prismatic               
    - prismatic -i SI100.XYZ             
    - command -v prismatic-gui           # [linux and interface == 'gui']
    - test -f $PREFIX/Applications/prismatic-gui.app/Contents/MacOS/prismatic-gui # [osx and interface == 'gui']
  imports:
    - pyprismatic


about:
  home: http://prism-em.com/
  license: GNU
  license_file: LICENSE
  summary: 'CPU / GPU software for fast simulation of Scanning Transmission Electron Microscopy (STEM) experiments'
  description: |
    CPU / GPU software for fast simulation of Scanning Transmission Electron Microscopy (STEM) experiments
  dev_url: https://github.com/prism-em/prismatic

extra:
  recipe-maintainers:
    - ericpre
    - douglowe
